language: node_js
node_js : 
 - 8.4.0
sudo: true
dist: trusty
cache:
  directories:
    - "node_modules"
env: 
 - DISPLAY=':99.0'
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable
install : 
  - "sudo apt install google-chrome-stable"
script:
 - "mocha testMocha/*.js"

