language: node_js
node_js : 
 - 8.4.0
sudo: false
env: 
 - DISPLAY=':99.0'
 - dist: trusty
 addons:
   - apt:
	- sources:
            - google-chrome
        - packages:
	    - google-chrome-stable
script:
 - "mocha testMocha/*.js"

