language: node_js
node_js : 
 - 8.4.0
sudo: true
dist: trusty
env: 
 - DISPLAY=':99.0'
install : 
  - "sudo apt install google-chrome"
  - "sudo apt install google-chrome-stable"
script:
 - "mocha testMocha/*.js"

