language: node_js
node_js : 
 - 8.4.0
sudo: true
dist: trusty
cache:
  directories:
    - "node_modules"
env: 
 - DISPLAY=':99.0'
 - SELENIUM_REMOTE_URL='http://localhost:4444/wd/hub'
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable
install : 
  - "npm install selenium-server-standalone"
  - "sudo apt install google-chrome-stable"
before_script : 
  - "java -jar selenium-server-standalone-2.53.1.jar"
script:
 - "mocha testMocha/*.js"

